# Generated by Django 5.2.12 on 2026-03-19 05:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
                ('model_no', models.IntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='total_spend_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.sqlquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.login')),
            ],
        ),
    ]
